In [1]:
run '/home/keir/Software/lya_emulator/plots/make_paper_plots_nCDM.py'


/share/apps/anaconda/python3.6/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
/home/keir/Software/lya_emulator/lyaemu/SimulationRunner/SimulationRunner/cambpower.py:8: UserWarning: 
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

The backend was *originally* set to 'module://ipykernel.pylab.backend_inline' by the following code:
  File "/share/apps/anaconda/python3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/share/apps/anaconda/python3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/share/apps/an

dpvals = [[0.73805814]
 [0.79181238]
 [0.84556662]
 [0.89932086]
 [0.95307511]
 [1.00682935]
 [1.06058359]
 [1.11433784]
 [1.16809208]
 [1.22184632]]
nuggets = [0.         0.0005202  0.0010404  0.00156061 0.00208081 0.00260101
 0.00312121 0.00364142 0.00416162 0.00468182 0.00520202 0.00572223
 0.00624243 0.00676263 0.00728283 0.00780304 0.00832324 0.00884344
 0.00936364 0.00988384 0.01040405 0.01092425 0.01144445 0.01196465
 0.01248486 0.01300506 0.01352526 0.01404546 0.01456567 0.01508587
 0.01560607 0.01612627 0.01664648 0.01716668 0.01768688 0.01820708
 0.01872728 0.01924749 0.01976769 0.02028789 0.02080809 0.0213283
 0.0218485  0.0223687  0.0228889  0.02340911 0.02392931 0.02444951
 0.02496971 0.02548992 0.02601012 0.02653032 0.02705052 0.02757072
 0.02809093 0.02861113 0.02913133 0.02965153 0.03017174 0.03069194
 0.03121214 0.03173234 0.03225255 0.03277275 0.03329295 0.03381315
 0.03433336 0.03485356 0.03537376 0.03589396 0.03641416 0.03693437
 0.03745457 0.03797477 0.03849497 0.0

Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    00s13  0001   2.055153e+05   2.767089e+12 
    03s27  0025  -1.823740e+05   1.321115e+06 
    07s20  0055  -1.834884e+05   7.451433e+02 
Runtime:     07s20
Optimization status: Converged

Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    00s14  0001  -1.849119e+05   2.505170e+10 
    03s18  0025  -2.111192e+05   1.199081e+06 
    10s80  0085  -2.111489e+05   8.616647e+00 
Runtime:     10s80
Optimization status: Converged

Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    02s30  0012  -2.105686e+05   2.674193e+07 
    08s50  0049  -2.146264e+05   9.609232e+01 
    12s70  0074  -2.146264e+05   9.609232e+01 
Runtime:     12s70
Optimization status: Errorb'ABNORMAL_TERMINATION_IN_LNSRCH'

Restarting optimization (not yet converged)
Getting data for mean flux sample number 0
Getting data for mean flux sampl

Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    02s24  0017  -1.689356e+05   5.105403e+07 
    08s51  0065  -1.750910e+05   3.201466e+03 
    11s37  0087  -1.750896e+05   3.201466e+03 
Runtime:     11s37
Optimization status: Errorb'ABNORMAL_TERMINATION_IN_LNSRCH'

Restarting optimization (not yet converged)
Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    00s14  0001  -1.467021e+05   9.210385e+10 
    03s23  0025  -2.041876e+05   2.059577e+06 
    11s61  0090  -2.047650e+05   1.751461e-01 
Runtime:     11s61
Optimization status: Errorb'ABNORMAL_TERMINATION_IN_LNSRCH'

Restarting optimization (not yet converged)
Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    00s14  0001  -1.950239e+05   1.209753e+10 
    03s20  0025  -2.147729e+05   7.903120e+05 
    08s32  0065  -2.148486e+05   4.488365e+01 
Runtime:     08s32
Optimization status: Converged

Ge

Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    00s00  0000   8.884101e+05           nan 
    02s18  0011  -1.563987e+05   7.674524e+07 
    09s11  0047  -1.708336e+05   1.845739e+03 
    12s85  0065  -1.708364e+05   5.599052e+02 
Runtime:     12s85
Optimization status: Converged

Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    00s19  0001  -1.491096e+05   8.820384e+10 
    03s50  0022  -2.043849e+05   3.747133e+07 
    12s33  0078  -2.050375e+05   2.519577e+02 
    16s75  0106  -2.050375e+05   4.570974e+02 
    20s53  0131  -2.050375e+05   4.570974e+02 
Runtime:     20s53
Optimization status: Errorb'ABNORMAL_TERMINATION_IN_LNSRCH'

Restarting optimization (not yet converged)
Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    00s12  0001  -1.826358e+05   2.281261e+10 
    03s22  0025  -2.121445e+05   3.369674e+06 
    09s82  0076  -2.125681e+05   

 /share/apps/anaconda/python3.6/lib/python3.6/site-packages/GPy/kern/src/rbf.py:43: RuntimeWarning:overflow encountered in square



    11s09  0088  -1.783049e+05   1.627228e+05 
Runtime:     11s09
Optimization status: Errorb'ABNORMAL_TERMINATION_IN_LNSRCH'

Restarting optimization (not yet converged)
Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    00s18  0001  -8.998632e+04   2.662059e+11 
    03s32  0025  -1.982098e+05   1.487421e+07 
    11s78  0089  -1.989508e+05   3.248366e+01 
    15s83  0119  -1.989508e+05   3.248366e+01 
Runtime:     15s83
Optimization status: Errorb'ABNORMAL_TERMINATION_IN_LNSRCH'

Restarting optimization (not yet converged)
Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    00s12  0001  -1.826732e+05   2.270770e+10 
    02s27  0017  -2.108502e+05   1.175512e+07 
    08s58  0066  -2.126399e+05   2.548083e+01 
    13s08  0100  -2.126400e+05   2.720844e+01 
Runtime:     13s08
Optimization status: Errorb'ABNORMAL_TERMINATION_IN_LNSRCH'

Restarting optimization (not yet converged)
Getting data for mea

Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    00s00  0000   4.151041e+05           nan 
    00s13  0001   4.151041e+05   6.064997e+12 
    03s30  0025  -1.771133e+05   4.938628e+06 
    08s41  0064  -1.781321e+05   2.367327e+00 
Runtime:     08s41
Optimization status: Converged

Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    01s15  0009  -1.888300e+05   6.166790e+07 
    05s34  0041  -1.988195e+05   4.982183e+03 
    11s10  0086  -1.988198e+05   1.478431e+03 
Runtime:     11s10
Optimization status: Errorb'ABNORMAL_TERMINATION_IN_LNSRCH'

Restarting optimization (not yet converged)
Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    01s20  0007  -2.014792e+05   8.723650e+07 
    05s32  0031  -2.106163e+05   7.475159e+05 
    13s01  0080  -2.106263e+05   2.253654e+01 
Runtime:     13s01
Optimization status: Errorb'ABNORMAL_TERMINATION_IN_LNSRCH'



Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    00s00  0000   8.841926e+05           nan 
    00s13  0001   8.841926e+05   1.831257e+13 
    03s32  0025  -1.696959e+05   6.227293e+06 
    07s21  0054  -1.709572e+05   8.454710e+01 
Runtime:     07s21
Optimization status: Converged

Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    00s12  0001  -1.497010e+05   8.713113e+10 
    03s35  0025  -2.047830e+05   8.011447e+06 
    12s21  0089  -2.051347e+05   4.262095e-01 
Runtime:     12s21
Optimization status: Errorb'ABNORMAL_TERMINATION_IN_LNSRCH'

Restarting optimization (not yet converged)
Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    01s21  0009  -1.692265e+05   3.729170e+08 
    06s44  0043  -1.924458e+05   5.210905e+03 
    08s09  0053  -1.924458e+05   5.210905e+03 
Runtime:     08s09
Optimization status: Converged

Getting data for mean flux sa

Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    01s19  0009  -1.875805e+05   9.524573e+06 
    05s39  0041   1.705367e+05   2.216447e+05 
    17s95  0136  -1.956694e+05   1.677622e+00 
    19s40  0147  -1.956694e+05   1.677622e+00 
Runtime:     19s40
Optimization status: Errorb'ABNORMAL_TERMINATION_IN_LNSRCH'

Restarting optimization (not yet converged)
Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    02s26  0017  -1.976048e+05   2.048330e+07 
    08s63  0064  -2.008602e+05   1.153520e+00 
    10s72  0080  -2.008602e+05   1.153520e+00 
Runtime:     10s72
Optimization status: Errorb'ABNORMAL_TERMINATION_IN_LNSRCH'

Restarting optimization (not yet converged)
Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    01s19  0009  -2.090505e+05   2.746994e+08 
    05s46  0041  -2.147278e+05   2.434042e+03 
    11s86  0089  -2.147278e+05   2.067030e+03 
Runtim

Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    00s13  0001   1.462952e+05   2.008684e+12 
    03s31  0025  -1.843641e+05   2.534689e+06 
    11s78  0089  -1.852711e+05   1.803943e+01 
    12s57  0095  -1.852711e+05   1.803943e+01 
Runtime:     12s57
Optimization status: Errorb'ABNORMAL_TERMINATION_IN_LNSRCH'

Restarting optimization (not yet converged)
Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    01s17  0009  -1.887418e+05   5.800060e+07 
    05s25  0041  -1.988318e+05   7.119562e+02 
    14s40  0109  -1.989078e+05   5.519789e+02 
Runtime:     14s40
Optimization status: Errorb'ABNORMAL_TERMINATION_IN_LNSRCH'

Restarting optimization (not yet converged)
Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    02s29  0016  -2.033321e+05   1.546926e+08 
    08s79  0062  -2.082109e+05   1.935414e+01 
    14s67  0104  -2.082109e+05   2.159846e+02 
Runtim

Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    00s00  0000   8.885328e+05           nan 
    01s15  0009  -1.506378e+05   1.040333e+09 
    05s50  0041  -1.708422e+05   1.680917e+04 
    06s48  0048  -1.708422e+05   1.680917e+04 
Runtime:     06s48
Optimization status: Converged

Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    00s12  0001  -1.490878e+05   8.806624e+10 
    03s27  0025  -2.047744e+05   1.888862e+06 
    11s78  0089  -2.050265e+05   3.485965e+01 
    12s95  0098  -2.050265e+05   3.485965e+01 
Runtime:     12s95
Optimization status: Errorb'ABNORMAL_TERMINATION_IN_LNSRCH'

Restarting optimization (not yet converged)
Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    00s13  0001   7.897847e+04   1.160081e+12 
    03s38  0025  -1.900790e+05   2.440979e+07 
    11s70  0088  -1.923571e+05   2.465163e+03 
Runtime:     11s70
Optimization s

Getting data for mean flux sample number 8
Getting data for mean flux sample number 9
Getting data for simulation number 27
k_max_emulated_h_Mpc = 28.093018599498517 0.19952623149688797 4.95 0.33
dpvals = [[0.73805814]
 [0.79181238]
 [0.84556662]
 [0.89932086]
 [0.95307511]
 [1.00682935]
 [1.06058359]
 [1.11433784]
 [1.16809208]
 [1.22184632]]
nuggets = [0.         0.0005202  0.0010404  0.00156061 0.00208081 0.00260101
 0.00312121 0.00364142 0.00416162 0.00468182 0.00520202 0.00572223
 0.00624243 0.00676263 0.00728283 0.00780304 0.00832324 0.00884344
 0.00936364 0.00988384 0.01040405 0.01092425 0.01144445 0.01196465
 0.01248486 0.01300506 0.01352526 0.01404546 0.01456567 0.01508587
 0.01560607 0.01612627 0.01664648 0.01716668 0.01768688 0.01820708
 0.01872728 0.01924749 0.01976769 0.02028789 0.02080809 0.0213283
 0.0218485  0.0223687  0.0228889  0.02340911 0.02392931 0.02444951
 0.02496971 0.02548992 0.02601012 0.02653032 0.02705052 0.02757072
 0.02809093 0.02861113 0.02913133 0.029651

 /share/apps/anaconda/python3.6/lib/python3.6/site-packages/GPy/kern/src/stationary.py:198: RuntimeWarning:invalid value encountered in true_divide


    05s88  0044  -2.111423e+05   2.254489e+05 
Runtime:     05s88
Optimization status: Converged

Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    01s16  0008  -1.846952e+05   2.285859e+07 
    05s37  0040  -2.010933e+05   2.868760e-01 
    11s29  0085  -2.010938e+05   9.615661e+00 
Runtime:     11s29
Optimization status: Errorb'ABNORMAL_TERMINATION_IN_LNSRCH'

Restarting optimization (not yet converged)
Getting data for mean flux sample number 0
Getting data for mean flux sample number 1
Getting data for mean flux sample number 2
Getting data for mean flux sample number 3
Getting data for mean flux sample number 4
Getting data for mean flux sample number 5
Getting data for mean flux sample number 6
Getting data for mean flux sample number 7
Getting data for mean flux sample number 8
Getting data for mean flux sample number 9
Getting data for simulation number 29
k_max_emulated_h_Mpc = 28.093018599498517 0.19952623149688797 4.95 0.33
dpval

Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    00s14  0001   4.131049e+05   6.011134e+12 
    02s24  0015  -1.709332e+05   7.422229e+07 
    08s69  0062  -1.781315e+05   1.524346e+04 
    13s29  0096  -1.781315e+05   1.524346e+04 
Runtime:     13s29
Optimization status: Converged

Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    01s19  0008  -1.884126e+05   8.912646e+06 
    05s44  0036  -1.988083e+05   3.527303e+00 
    14s57  0098  -1.988086e+05   1.216943e+02 
Runtime:     14s57
Optimization status: Errorb'ABNORMAL_TERMINATION_IN_LNSRCH'

Restarting optimization (not yet converged)
Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    00s12  0001   7.855743e+04   1.153560e+12 
    03s21  0025  -1.895984e+05   6.807297e+06 
    11s58  0088  -1.923269e+05   8.225494e+02 
Runtime:     11s58
Optimization status: Errorb'ABNORMAL_TERMINATION_IN_LNSRCH'


Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    00s00  0000   5.885266e+05           nan 
    01s19  0008  -1.539889e+05   3.502873e+08 
    05s31  0036  -1.748719e+05   3.599532e+05 
    15s42  0105  -1.748866e+05   6.433354e-01 
Runtime:     15s42
Optimization status: Errorb'ABNORMAL_TERMINATION_IN_LNSRCH'

Restarting optimization (not yet converged)
Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    00s00  0000  -1.461948e+05           nan 
    03s21  0016  -2.018094e+05   1.750005e+07 
    10s96  0056  -2.045454e+05   6.741035e+01 
    20s83  0110  -2.045454e+05   6.416498e+01 
Runtime:     20s83
Optimization status: Errorb'ABNORMAL_TERMINATION_IN_LNSRCH'

Restarting optimization (not yet converged)
Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    01s32  0009  -2.090541e+05   2.740874e+08 
    06s65  0040  -2.146587e+05   3.207776e+02 
    15s3

Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    01s26  0009  -1.615570e+05   5.018732e+08 
    05s63  0041  -1.781705e+05   1.123262e+04 
    11s71  0086  -1.781700e+05   9.412205e+03 
Runtime:     11s71
Optimization status: Errorb'ABNORMAL_TERMINATION_IN_LNSRCH'

Restarting optimization (not yet converged)
Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    01s30  0009  -1.888253e+05   6.219603e+07 
    05s67  0040  -1.988734e+05   1.331457e+03 
    07s82  0055  -1.988872e+05   1.429970e+00 
    09s79  0069  -1.988875e+05   6.757726e-02 
Runtime:     09s79
Optimization status: Converged

Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    01s29  0009  -2.026510e+05   3.876526e+08 
    05s59  0041  -2.106765e+05   4.062463e+00 
    09s43  0070  -2.106765e+05   4.062463e+00 
Runtime:     09s43
Optimization status: Converged

Getting data for mean flux s

Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    01s02  0005  -1.874178e+05   9.882068e+07 
    05s56  0028  -1.957911e+05   2.971846e+06 
    18s74  0094  -1.959110e+05   2.473923e+02 
    24s92  0125  -1.959110e+05   2.540743e+02 
Runtime:     24s92
Optimization status: Converged

Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    02s33  0010  -1.921408e+05   7.316773e+07 
    09s03  0043  -2.009824e+05   6.401797e+02 
    10s15  0049  -2.009824e+05   6.401797e+02 
Runtime:     10s15
Optimization status: Converged

Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    02s26  0016  -2.132788e+05   2.223783e+07 
    07s83  0054  -2.148617e+05   7.341491e+02 
    08s97  0062  -2.148617e+05   7.330385e+02 
    16s41  0114  -2.148617e+05   6.122815e+02 
Runtime:     16s41
Optimization status: Errorb'ABNORMAL_TERMINATION_IN_LNSRCH'

Restarting optimization (

Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    01s18  0009  -1.723533e+05   1.523629e+07 
    05s41  0041  -1.854607e+05   3.257562e+04 
    13s83  0105  -1.854609e+05   4.986338e+03 
Runtime:     13s83
Optimization status: Errorb'ABNORMAL_TERMINATION_IN_LNSRCH'

Restarting optimization (not yet converged)
Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    00s15  0001  -8.504989e+04   2.911797e+11 
    03s32  0025  -1.973217e+05   1.133184e+07 
    10s84  0082  -1.984090e+05   1.662457e+02 
Runtime:     10s84
Optimization status: Errorb'ABNORMAL_TERMINATION_IN_LNSRCH'

Restarting optimization (not yet converged)
Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    02s21  0013  -2.028214e+05   1.024916e+07 
    08s50  0049  -2.081978e+05   6.785610e+02 
    13s80  0080  -2.081978e+05   6.353658e+02 
Runtime:     13s80
Optimization status: Errorb'ABNORM

Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    01s18  0009  -1.690885e+05   1.183010e+08 
    05s41  0041  -1.833546e+05   7.452247e+01 
    17s02  0129  -1.833543e+05   8.099784e+01 
    19s76  0150  -1.833544e+05   8.099784e+01 
Runtime:     19s76
Optimization status: Errorb'ABNORMAL_TERMINATION_IN_LNSRCH'

Restarting optimization (not yet converged)
Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    01s26  0009  -2.067338e+05   1.819882e+08 
    05s64  0040  -2.109940e+05   6.254265e+00 
    09s59  0068  -2.109940e+05   6.254265e+00 
Runtime:     09s59
Optimization status: Converged

Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    02s28  0017  -2.131414e+05   1.125317e+07 
    08s73  0065  -2.145350e+05   5.805571e+02 
    09s81  0073  -2.145350e+05   5.805571e+02 
Runtime:     09s81
Optimization status: Errorb'ABNORMAL_TERMINATION_IN_LNSRCH'


Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    01s27  0009  -1.619791e+05   2.412947e+08 
    06s42  0044  -1.783524e+05   9.261326e+04 
    11s96  0082  -1.783909e+05   1.094087e+01 
Runtime:     11s96
Optimization status: Converged

Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    01s06  0006  -1.894216e+05   3.863289e+07 
    04s20  0024  -1.981050e+05   9.162473e+06 
    14s23  0086  -1.990648e+05   1.591457e+02 
    16s58  0100  -1.990648e+05   1.591457e+02 
Runtime:     16s58
Optimization status: Errorb'ABNORMAL_TERMINATION_IN_LNSRCH'

Restarting optimization (not yet converged)
Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    00s14  0001  -1.850277e+05   2.094180e+10 
    03s38  0024  -2.125170e+05   1.026735e+07 
    11s80  0082  -2.128844e+05   4.784215e+02 
    12s81  0089  -2.128844e+05   4.784215e+02 
Runtime:     12s81
Optimization 

Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    00s13  0001   1.323790e+05   1.911046e+12 
    03s27  0025  -1.841411e+05   4.657590e+07 
    11s68  0089  -1.849435e+05   9.661743e+00 
    20s46  0156  -1.849437e+05   2.435293e+00 
Runtime:     20s46
Optimization status: Errorb'ABNORMAL_TERMINATION_IN_LNSRCH'

Restarting optimization (not yet converged)
Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    00s00  0000  -1.321364e+05           nan 
    02s12  0011  -1.958125e+05   9.411406e+07 
    08s53  0047  -2.023244e+05   1.059290e+00 
    10s87  0059  -2.023245e+05   2.234575e-01 
Runtime:     10s87
Optimization status: Converged

Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    02s36  0015  -2.078525e+05   7.548694e+07 
    08s79  0056  -2.105017e+05   9.676845e+02 
    12s40  0079  -2.105017e+05   9.600938e+02 
Runtime:     12s40
Optimization s

Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    02s35  0017  -1.792205e+05   6.949244e+07 
    08s82  0065  -1.655915e+05   3.822091e+09 
    11s38  0084  -1.838466e+05   1.083874e+04 
Runtime:     11s38
Optimization status: Errorb'ABNORMAL_TERMINATION_IN_LNSRCH'

Restarting optimization (not yet converged)
Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    00s13  0001  -8.600142e+04   2.831537e+11 
    03s29  0025  -1.964124e+05   1.504107e+07 
    08s83  0067  -1.977382e+05   1.783567e+01 
Runtime:     08s83
Optimization status: Converged

Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    00s00  0000  -1.590528e+05           nan 
    01s18  0009  -1.969404e+05   6.037656e+07 
    05s41  0041  -2.074810e+05   2.408340e+01 
    09s84  0074  -2.074814e+05   1.914483e+01 
Runtime:     09s84
Optimization status: Converged

Getting data for mean flux sa

Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    01s16  0009  -1.712253e+05   2.333509e+07 
    05s29  0041  -1.853643e+05   2.813487e+01 
    08s43  0065  -1.853644e+05   3.889101e+02 
Runtime:     08s43
Optimization status: Converged

Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    00s12  0001  -9.453356e+04   2.488495e+11 
    03s46  0019  -1.956730e+05   1.094644e+08 
    11s23  0065   1.657986e+05   1.967234e+03 
    19s27  0111  -1.988343e+05   4.789080e+02 
Runtime:     19s27
Optimization status: Errorb'ABNORMAL_TERMINATION_IN_LNSRCH'

Restarting optimization (not yet converged)
Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    03s54  0017  -2.035297e+05   9.263693e+07 
    12s43  0060  -2.076966e+05   2.688469e+02 
    17s78  0086  -2.076967e+05   2.451704e+02 
Runtime:     17s78
Optimization status: Errorb'ABNORMAL_TERMINATION_IN_LNSRCH'


Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    02s26  0016  -1.981137e+05   3.513265e+06 
    08s81  0063  -2.005832e+05   1.575664e+02 
    11s63  0084  -2.005832e+05   1.575664e+02 
Runtime:     11s63
Optimization status: Errorb'ABNORMAL_TERMINATION_IN_LNSRCH'

Restarting optimization (not yet converged)
Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    00s12  0001  -1.769548e+05   3.531576e+10 
    03s28  0025  -2.090155e+05   4.793364e+06 
    11s72  0089  -2.090710e+05   1.916705e+03 
    18s16  0139  -2.090710e+05   2.005276e+01 
Runtime:     18s16
Optimization status: Errorb'ABNORMAL_TERMINATION_IN_LNSRCH'

Restarting optimization (not yet converged)
Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    01s22  0008  -1.850803e+05   2.506211e+07 
    05s30  0036  -2.013818e+05   7.430030e+03 
    11s26  0077  -2.013823e+05   7.430030e+03 
Runtim

Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    01s16  0009  -1.702927e+05   3.998428e+07 
    05s36  0041  -1.841409e+05   5.947267e+03 
    11s93  0092  -1.841405e+05   4.846706e+03 
Runtime:     11s93
Optimization status: Errorb'ABNORMAL_TERMINATION_IN_LNSRCH'

Restarting optimization (not yet converged)
Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    00s14  0001  -8.516902e+04   2.891851e+11 
    03s28  0025  -1.969494e+05   1.320552e+07 
    09s28  0071  -1.980320e+05   5.613299e+01 
Runtime:     09s28
Optimization status: Errorb'ABNORMAL_TERMINATION_IN_LNSRCH'

Restarting optimization (not yet converged)
Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    01s12  0008  -1.850426e+05   3.145137e+07 
    05s26  0040  -2.014249e+05   7.834651e+01 
    10s08  0077  -2.014247e+05   7.834651e+01 
Runtime:     10s08
Optimization status: Errorb'ABNORM

Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    00s13  0001  -1.256787e+05   1.500367e+11 
    03s35  0025  -2.005025e+05   2.602667e+06 
    05s48  0041  -2.008111e+05   5.053772e-01 
    10s58  0079  -2.008111e+05   5.053772e-01 
Runtime:     10s58
Optimization status: Errorb'ABNORMAL_TERMINATION_IN_LNSRCH'

Restarting optimization (not yet converged)
Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    00s16  0001  -1.773261e+05   3.482961e+10 
    03s45  0019  -2.082428e+05   7.822522e+05 
    12s07  0067  -2.092439e+05   7.156548e+01 
    16s30  0091  -2.092438e+05   7.156548e+01 
Runtime:     16s30
Optimization status: Errorb'ABNORMAL_TERMINATION_IN_LNSRCH'

Restarting optimization (not yet converged)
Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    01s26  0007  -1.846971e+05   2.910356e+07 
    05s48  0035  -2.014977e+05   7.090862e+02 
    12

Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    02s33  0017  -1.794567e+05   4.737283e+07 
    08s70  0064  -1.838679e+05   3.785970e+02 
    12s16  0088  -1.838679e+05   3.785970e+02 
Runtime:     12s16
Optimization status: Errorb'ABNORMAL_TERMINATION_IN_LNSRCH'

Restarting optimization (not yet converged)
Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    00s00  0000  -8.403167e+04           nan 
    02s35  0017  -1.941058e+05   4.892429e+07 
    08s74  0063  -1.978054e+05   4.506339e+02 
    10s96  0079  -1.978054e+05   4.506339e+02 
Runtime:     10s96
Optimization status: Errorb'ABNORMAL_TERMINATION_IN_LNSRCH'

Restarting optimization (not yet converged)
Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    01s18  0009  -1.975660e+05   6.175399e+07 
    05s45  0041  -2.079365e+05   1.469991e+03 
    11s08  0084  -2.079366e+05   4.397815e+02 
Runtime

Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    00s16  0001  -2.993011e+04   5.285582e+11 
    04s40  0025  -1.921085e+05   6.818350e+06 
    13s03  0078  -1.926447e+05   1.707661e+04 
Runtime:     13s03
Optimization status: Errorb'ABNORMAL_TERMINATION_IN_LNSRCH'

Restarting optimization (not yet converged)
Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    00s00  0000  -1.499955e+05           nan 
    01s25  0009  -1.961978e+05   6.833853e+07 
    06s39  0043  -2.055750e+05   1.344304e+02 
    12s20  0076  -2.055750e+05   1.344304e+02 
Runtime:     12s20
Optimization status: Errorb'ABNORMAL_TERMINATION_IN_LNSRCH'

Restarting optimization (not yet converged)
Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    00s00  0000  -1.756115e+05           nan 
    02s14  0011  -2.046786e+05   8.797738e+07 
    08s97  0046  -2.120209e+05   5.501542e+00 
    15s0

Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    00s14  0001   1.100039e+05   1.644765e+12 
    03s40  0024  -1.835642e+05   7.817183e+07 
    11s97  0084  -1.856767e+05   6.286359e+03 
    12s68  0089  -1.856767e+05   6.286359e+03 
Runtime:     12s68
Optimization status: Errorb'ABNORMAL_TERMINATION_IN_LNSRCH'

Restarting optimization (not yet converged)
Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    01s21  0009  -1.896563e+05   6.726503e+07 
    05s54  0041  -1.995029e+05   2.263188e+00 
    10s58  0078  -1.995030e+05   2.264668e+00 
Runtime:     10s58
Optimization status: Converged

Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    01s20  0009  -1.991703e+05   4.588330e+08 
    05s41  0041  -2.084651e+05   2.777562e+05 
    12s49  0095  -2.084742e+05   3.579705e+01 
Runtime:     12s49
Optimization status: Errorb'ABNORMAL_TERMINATION_IN_LNSRCH'


Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    02s28  0016  -1.793299e+05   1.258491e+08 
    08s95  0064  -1.839914e+05   2.746684e+01 
    10s20  0073  -1.839914e+05   2.746684e+01 
Runtime:     10s20
Optimization status: Converged

Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    01s21  0009  -1.887319e+05   2.284578e+07 
    05s55  0041  -1.982122e+05   4.868720e+00 
    13s48  0098  -1.982123e+05   4.030626e+00 
Runtime:     13s48
Optimization status: Errorb'ABNORMAL_TERMINATION_IN_LNSRCH'

Restarting optimization (not yet converged)
Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    00s14  0001  -1.682223e+05   4.053617e+10 
    02s21  0015  -2.057971e+05   7.341483e+07 
    08s69  0062  -2.087413e+05   1.080862e+01 
    16s61  0116  -2.087414e+05   8.631139e+00 
Runtime:     16s61
Optimization status: Errorb'ABNORMAL_TERMINATION_IN_LNSRCH'


Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    00s00  0000   1.615705e+05           nan 
    02s16  0013  -1.761869e+05   2.554630e+08 
    08s88  0054  -1.838247e+05   1.413046e+02 
    13s19  0080  -1.838254e+05   2.733834e+02 
Runtime:     13s19
Optimization status: Errorb'ABNORMAL_TERMINATION_IN_LNSRCH'

Restarting optimization (not yet converged)
Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    01s22  0009  -1.880874e+05   6.195707e+07 
    06s59  0047  -1.978466e+05   4.388099e+01 
    13s49  0097  -1.978467e+05   4.364290e+01 
Runtime:     13s49
Optimization status: Errorb'ABNORMAL_TERMINATION_IN_LNSRCH'

Restarting optimization (not yet converged)
Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    01s21  0009  -2.021965e+05   3.878473e+08 
    05s52  0041  -2.102658e+05   3.941695e-01 
    10s83  0080  -2.102659e+05   1.464263e+00 
Runtime

 /share/apps/anaconda/python3.6/lib/python3.6/site-packages/GPy/kern/src/stationary.py:167: RuntimeWarning:divide by zero encountered in true_divide
 /share/apps/anaconda/python3.6/lib/python3.6/site-packages/GPy/kern/src/stationary.py:167: RuntimeWarning:invalid value encountered in true_divide
 /share/apps/anaconda/python3.6/lib/python3.6/site-packages/GPy/kern/src/rbf.py:46: RuntimeWarning:invalid value encountered in multiply


    11s69  0074           nan           nan 

 /share/apps/anaconda/python3.6/lib/python3.6/site-packages/paramz/optimization/verbose_optimization.py:160: RuntimeWarning:invalid value encountered in less


    13s27  0086           nan   3.910322e+07 
Runtime:     13s27
Optimization status: Errorb'ABNORMAL_TERMINATION_IN_LNSRCH'

Restarting optimization (not yet converged)
Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    00s17  0001  -9.568293e+04   2.333991e+11 
    03s34  0022  -1.978701e+05   1.445578e+07 
    12s04  0080  -1.992166e+05   7.031867e+01 
    23s73  0161  -1.992167e+05   6.911607e+01 
Runtime:     23s73
Optimization status: Errorb'ABNORMAL_TERMINATION_IN_LNSRCH'

Restarting optimization (not yet converged)
Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    00s13  0001  -1.589618e+05   5.546567e+10 
    03s34  0024  -2.058253e+05   5.479246e+07 
    08s32  0061  -2.078372e+05   1.129359e-01 
Runtime:     08s32
Optimization status: Converged

Getting data for mean flux sample number 0
Getting data for mean flux sample number 1
Getting data for mean flux sample number 2
Getting data 

Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    03s49  0017  -1.812217e+05   8.136996e+06 
    11s35  0060  -1.852233e+05   4.416004e+01 
    17s24  0094  -1.852233e+05   4.416004e+01 
Runtime:     17s24
Optimization status: Errorb'ABNORMAL_TERMINATION_IN_LNSRCH'

Restarting optimization (not yet converged)
Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    02s30  0017  -1.951454e+05   2.631145e+07 
    08s77  0064  -1.984804e+05   4.296282e+02 
    10s88  0079  -1.984803e+05   4.296282e+02 
Runtime:     10s88
Optimization status: Errorb'ABNORMAL_TERMINATION_IN_LNSRCH'

Restarting optimization (not yet converged)
Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    02s17  0016  -2.033345e+05   1.506232e+08 
    08s41  0064  -2.079840e+05   1.081910e+00 
    15s17  0107  -2.079840e+05   1.067931e+00 
Runtime:     15s17
Optimization status: Errorb'ABNORM

Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    00s12  0001   1.584414e+05   2.168244e+12 
    03s25  0025  -1.830659e+05   3.668021e+05 
    11s84  0089  -1.839228e+05   8.423550e+03 
    12s28  0092  -1.839231e+05   8.760353e+03 
Runtime:     12s28
Optimization status: Errorb'ABNORMAL_TERMINATION_IN_LNSRCH'

Restarting optimization (not yet converged)
Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    00s00  0000  -8.906967e+04           nan 
    02s16  0014  -1.927721e+05   3.824219e+08 
    08s51  0056  -1.981923e+05   2.603582e+01 
    14s61  0096  -1.981926e+05   1.145719e+01 
Runtime:     14s61
Optimization status: Errorb'ABNORMAL_TERMINATION_IN_LNSRCH'

Restarting optimization (not yet converged)
Running L-BFGS-B (Scipy implementation) Code:
  runtime   i      f              |g|        
    01s15  0009  -2.025558e+05   3.822756e+08 
    05s49  0041  -2.107453e+05   9.959958e+01 
    10s

In [2]:
k


array([ 0.62831853,  1.25663706,  1.88495559,  2.51327412,  3.14159265,
        3.76991118,  4.39822972,  5.02654825,  5.65486678,  6.28318531,
        6.91150384,  7.53982237,  8.1681409 ,  8.79645943,  9.42477796,
       10.05309649, 10.68141502, 11.30973355, 11.93805208, 12.56637061,
       13.19468915, 13.82300768, 14.45132621, 15.07964474, 15.70796327,
       16.3362818 , 16.96460033, 17.59291886, 18.22123739, 18.84955592,
       19.47787445, 20.10619298, 20.73451151, 21.36283004, 21.99114858,
       22.61946711, 23.24778564, 23.87610417, 24.5044227 , 25.13274123,
       25.76105976, 26.38937829, 27.01769682, 27.64601535, 28.27433388,
       28.90265241, 29.53097094, 30.15928947, 30.78760801, 31.41592654,
       32.04424507, 32.6725636 , 33.30088213, 33.92920066, 34.55751919,
       35.18583772, 35.81415625, 36.44247478, 37.07079331, 37.69911184,
       38.32743037, 38.9557489 , 39.58406744, 40.21238597, 40.8407045 ,
       41.46902303, 42.09734156, 42.72566009, 43.35397862, 43.98

In [3]:
z


array([4.95, 4.58, 4.24])

In [4]:
p


array([[7.38058135e-01, 9.25650000e-01, 2.17500000e-09, ...,
        2.08613324e+01, 2.34887897e+01, 2.25528601e+01],
       [7.38578338e-01, 9.27550000e-01, 2.22700000e-09, ...,
        1.49474409e+01, 1.76822913e+01, 2.02114195e+01],
       [7.39098540e-01, 9.56050000e-01, 2.38300000e-09, ...,
        1.47724644e+01, 1.82690473e+01, 2.16089526e+01],
       ...,
       [1.26866454e+00, 9.58035727e-01, 1.89078126e-09, ...,
        8.56580189e+00, 1.03248813e+01, 1.17978008e+01],
       [1.26918474e+00, 9.66174951e-01, 1.79878570e-09, ...,
        7.99364485e+00, 9.65611592e+00, 1.10826782e+01],
       [1.26970494e+00, 9.56507644e-01, 1.87034675e-09, ...,
        1.06090833e+01, 1.32262155e+01, 1.55709103e+01]])

In [5]:
f


array([[1.14996316e+02, 8.62794969e+01, 6.35965674e+01, ...,
        8.32040401e-05, 7.41588909e-05, 6.63573837e-05],
       [1.28810946e+02, 9.92283945e+01, 7.45628309e+01, ...,
        2.48322339e-04, 2.21693365e-04, 1.99864117e-04],
       [1.30098140e+02, 9.50583495e+01, 6.52510913e+01, ...,
        9.42441642e-06, 8.52443612e-06, 7.64451869e-06],
       ...,
       [2.70794732e+02, 2.23552887e+02, 1.74324994e+02, ...,
        1.08294521e-03, 9.57205126e-04, 8.43861074e-04],
       [2.68148579e+02, 2.17704159e+02, 1.70679979e+02, ...,
        1.72984522e-03, 1.58086140e-03, 1.38496628e-03],
       [2.88200171e+02, 2.37223578e+02, 1.85239978e+02, ...,
        8.94896085e-04, 8.00171527e-04, 7.18433072e-04]])

In [6]:
m


array([[ 9.11309333e+01,  7.21195999e+01,  5.39349708e+01, ...,
         1.19905005e-01,  1.30613014e-01,  1.16215478e-01],
       [ 1.45161072e+02,  1.05593078e+02,  7.66377473e+01, ...,
         6.88998469e-02,  5.02538810e-02,  4.67990886e-02],
       [ 1.21471839e+02,  9.22466172e+01,  6.62031021e+01, ...,
        -2.23115418e-02, -6.66660383e-02, -1.21589682e-01],
       ...,
       [ 2.71968320e+02,  2.25159810e+02,  1.74904781e+02, ...,
         2.76494615e-01,  2.42170808e-01,  2.27483056e-01],
       [ 2.63638354e+02,  2.12944815e+02,  1.67407793e+02, ...,
         2.89776432e-01,  2.61718372e-01,  2.32273294e-01],
       [ 2.89602833e+02,  2.38954595e+02,  1.85634909e+02, ...,
         1.32071643e-01,  1.07240992e-01,  1.09417923e-01]])

In [7]:
s


array([[7.71223433e+02, 5.80231778e+02, 4.28094023e+02, ...,
        1.01421601e-01, 8.80838020e-02, 7.75502051e-02],
       [4.58798827e+02, 3.63882499e+02, 2.80336611e+02, ...,
        1.86736111e-01, 1.66408763e-01, 1.51162426e-01],
       [9.03006427e+02, 6.84060152e+02, 5.31116730e+02, ...,
        2.93122499e-01, 2.64260257e-01, 2.41913806e-01],
       ...,
       [1.15557271e+01, 9.20853070e+00, 6.94800203e+00, ...,
        3.61555890e-03, 3.22198359e-03, 2.92678610e-03],
       [1.37691765e+01, 1.09723848e+01, 8.27886171e+00, ...,
        5.61157770e-03, 5.00072374e-03, 4.54255844e-03],
       [8.44179268e+00, 6.72709787e+00, 5.07571633e+00, ...,
        3.76866922e-03, 3.36021132e-03, 3.00098146e-03]])

In [8]:
k_max


28.093018599498517

In [17]:
k.shape, z.shape, p.shape, f.shape, m.shape, s.shape


((89,), (3,), (930, 16), (930, 267), (930, 135), (930, 135))

In [18]:
#Save cross-validation data
np.savez('/home/keir/Software/lya_emulator/plots/cross_validation.npz', k=k, z=z, p=p, f=f, m=m, s=s, k_max=k_max)


In [13]:
i = 92

(m[i][:45] - f[i, :45]) / s[i][:45]


array([-0.00102681,  0.08102066, -0.01527028, -0.02811564,  0.00127899,
        0.0406711 ,  0.04700589, -0.03519771, -0.12728187, -0.09692994,
       -0.02927088, -0.06156393, -0.13453461, -0.13726537, -0.19999987,
       -0.09516649, -0.24420664, -0.18084628, -0.33716218, -0.1628375 ,
       -0.40370729, -0.60605692, -0.55181101, -0.41120509, -0.37352872,
       -0.68723744, -0.34570838, -0.29612433,  0.10687974, -0.36095641,
       -0.36904589,  0.02779916, -0.31556346,  0.06829211, -0.28260157,
       -0.63318856, -0.30933021, -0.13037089, -0.32306752, -0.4625152 ,
       -0.07129386, -0.98470192,  0.16761517,  0.85811509, -0.04254951])

In [14]:
s[i][:45] / f[i, :45]


array([0.06135512, 0.06359002, 0.06086595, 0.06095585, 0.05971517,
       0.0595741 , 0.05935345, 0.05984876, 0.06025014, 0.06102343,
       0.05846016, 0.058896  , 0.06017368, 0.05802037, 0.05977793,
       0.05814621, 0.05821136, 0.059668  , 0.05939347, 0.05834354,
       0.05757304, 0.05835965, 0.0571203 , 0.05623516, 0.05728673,
       0.05736713, 0.0575542 , 0.05678608, 0.05706495, 0.05736869,
       0.05795544, 0.05773527, 0.05830395, 0.0587953 , 0.05895953,
       0.05775044, 0.05874293, 0.05915508, 0.05826037, 0.05791185,
       0.05994743, 0.05854649, 0.05963146, 0.05900808, 0.05999162])

In [15]:
s[i][:45] / m[i][:45]


array([0.06135899, 0.06326408, 0.06092258, 0.06106049, 0.05971061,
       0.05943011, 0.05918832, 0.0599751 , 0.06071575, 0.06138654,
       0.05856037, 0.05911033, 0.06066479, 0.05848617, 0.06050126,
       0.05846975, 0.0590508 , 0.06031889, 0.06060714, 0.05890315,
       0.05894303, 0.06049947, 0.05897931, 0.05756633, 0.05853937,
       0.05972165, 0.05872261, 0.05775732, 0.05671902, 0.05858178,
       0.0592221 , 0.05764276, 0.05939677, 0.05856016, 0.05995856,
       0.05994234, 0.0598301 , 0.05961484, 0.05937798, 0.05950571,
       0.06020474, 0.06212823, 0.05904134, 0.05616417, 0.06014515])

In [16]:
(m[i][:45] - f[i, :45]) / f[i, :45]


array([-6.30001681e-05,  5.15210554e-03, -9.29440198e-04, -1.71381279e-03,
        7.63753185e-05,  2.42294415e-03,  2.78996187e-03, -2.10653935e-03,
       -7.66874973e-03, -5.91499813e-03, -1.71118045e-03, -3.62586969e-03,
       -8.09544258e-03, -7.96418749e-03, -1.19555792e-02, -5.53357047e-03,
       -1.42155999e-02, -1.07907363e-02, -2.00252320e-02, -9.50051559e-03,
       -2.32426562e-02, -3.53692697e-02, -3.15196114e-02, -2.31241833e-02,
       -2.13982380e-02, -3.94248412e-02, -1.98969704e-02, -1.68157413e-02,
        6.09908682e-03, -2.07075960e-02, -2.13882184e-02,  1.60499210e-03,
       -1.83985967e-02,  4.01525483e-03, -1.66620549e-02, -3.65669162e-02,
       -1.81709633e-02, -7.71210066e-03, -1.88220315e-02, -2.67851094e-02,
       -4.27388369e-03, -5.76508390e-02,  9.99513784e-03,  5.06357251e-02,
       -2.55261395e-03])